title: Yitian Wang
description: Yitian Wang's personal website, showcasing his academic and professional achievements, projects, and contact information.
url: "https://cosmotim.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: default
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CV_Latex/WebsiteLink.md
  - vendor
include:
  - CV_Latex/Curriculum_Vitae_YitianWang.pdf
  - CV_Latex/Resume_Battery_General.pdf
  - CV_Latex/Resume_Semiconductor_General.pdf
